### ISSUE TITLE
Will you get banned for using NOWT?

### ISSUE THREAD

**Issue by dhilanpatel30** [pwall2222/NOWT#12]
Being completely honest, won't you get banned for 3rd party software, since riot bans stuff that's not tracker/blitz?

**Comment by pwall2222** [comment]
Look, I have been using WAIUA/NOWT, since 2021.
If you belive in the fear mongering missinformation people put out there it's up to you.
RiotGames will only ban you for doing things they dislike (like showing streamer mode names {which is not possible in NOWT}).
People that are said to be baned for third party programs are just coping with reality and blame shifting.
And if my experience using this programs and me literally being a developer in the scene for years is not enough proof for you (which is fine), just use Tracker.GG it's not so bad for the average user, although it doesn't show skinks.

**Comment by dhilanpatel30** [comment]
so if you can’t see people’s names that are on streamer mode, what more can
NOWT do than tracker other than show skins?
